# Generated by Django 3.1.1 on 2020-09-21 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th')])),
                ('sub_1', models.CharField(max_length=20)),
                ('sub_2', models.CharField(max_length=20)),
                ('sub_3', models.CharField(max_length=20)),
                ('sub_4', models.CharField(max_length=20)),
                ('sub_5', models.CharField(max_length=20, null=True)),
                ('sub_6', models.CharField(max_length=20, null=True)),
                ('timeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
