# Generated by Django 3.1.1 on 2020-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
