# Generated by Django 3.1.1 on 2020-09-23 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
