# Generated by Django 3.1.1 on 2020-10-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200923_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_year',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='first_year',
            name='result',
            field=models.CharField(default='FAIL', max_length=4),
        ),
        migrations.AddField(
            model_name='first_year',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='second_year',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='second_year',
            name='result',
            field=models.CharField(default='FAIL', max_length=4),
        ),
        migrations.AddField(
            model_name='second_year',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='third_year',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='third_year',
            name='result',
            field=models.CharField(default='FAIL', max_length=4),
        ),
        migrations.AddField(
            model_name='third_year',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
