# Generated by Django 3.1.1 on 2020-10-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201025_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
        migrations.AlterField(
            model_name='first_year',
            name='percentage',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='second_year',
            name='percentage',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='third_year',
            name='percentage',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
